version: 2

builds:
  - binary: spec-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/9Ashwin/spec-cli/internal/build.Version={{ .Version }} -X github.com/9Ashwin/spec-cli/internal/build.Date={{ .Date }} -X github.com/9Ashwin/spec-cli/internal/build.CommitHash={{ .ShortCommit }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "spec-cli-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
