#!/usr/bin/env sh
set -e

export PATH="$HOME/.local/share/mise/shims:$HOME/.local/bin:$HOME/.npm-global/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"

echo "Checking Go formatting and vet..."
make fmt-check
make vet
